batch_size: 128
dataset_path: cfpark00/toy-multistep-nn_10-na_5-nab_10-seed_0
dataset_split: train
instruct_mode: false
model_name: cfpark00/toy-multistep-nn_10-na_5
model_parallel: false
save_path: ./data/sft/toy-multistep-nn_10-na_5-nab_10-seed_0
train_max_length: 64
training_arguments:
  bf16: false
  gradient_accumulation_steps: 1
  learning_rate: 0.001
  logging_steps: 12
  lr_scheduler_type: linear
  num_train_epochs: 1
  save_only_model: true
  save_steps: 0.2
  save_strategy: steps
  warmup_ratio: 0.05
wandb:
  project_name: toy-multistep-reasoning
  run_name: toy-multistep-reasoning-example-nn_10-na_5-nab_10-seed_0
